#!/bin/bash

echo "run dbconnector using sbt run"

pushd ../QvantelDBConnector/

echo "now we are running sbt to start the dbconnector."
echo "dbconnector is running now.."
echo $limit

# Get data from cassandra and add to file
echo "getting data from cassandra and writing it to files!"
docker exec -i "$cass_container_name" cqlsh << EOF > "$temp_cass_service_file"
use $cassandra_keyspace;
select service FROM $cassandra_cdr_table_name limit 10;
EOF
docker exec -i "$cass_container_name" cqlsh << EOF > "$temp_cass_createdAt_file"
use $cassandra_keyspace;
select created_at FROM "$cassandra_cdr_table_name" limit 10;
EOF
docker exec -i "$cass_container_name" cqlsh << EOF > "$temp_cass_eventDetails_file"
use $cassandra_keyspace;
select event_details FROM "$cassandra_cdr_table_name" limit 10; 
EOF
docker exec -i "$cass_container_name" cqlsh << EOF > "$temp_cass_usedServiceUnit_file"
use $cassandra_keyspace;
select used_service_units FROM "$cassandra_cdr_table_name" limit 10; 
EOF

# Read from file and grep for rows.
echo "reading data from file"
has_service=$(cat "$temp_cass_service_file" | grep -oP '[a-z,A-Z]*')
has_createdAt=$(cat "$temp_cass_createdAt_file" | grep -oP '[0-9]*[0-9]')
has_eventDeta=$(cat "$temp_cass_eventDetails_file" | grep -oP '[a-z,A-Z]*')
has_usedService=$(cat "$temp_cass_usedServiceUnit_file" | grep -oP '[a-z,A-Z]*') #-oP \s+[0-9]+

#popd
#pwd
